//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cake()
        {
            this.order_cake = new HashSet<order_cake>();
        }
    
        public string idCake { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> price { get; set; }
        public string category_idcategory { get; set; }
        public byte[] image { get; set; }
        public string name_cake { get; set; }
        public string description { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_cake> order_cake { get; set; }
    }
}
