//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_order()
        {
            this.order_cake = new HashSet<order_cake>();
        }
    
        public int idOrder { get; set; }
        public Nullable<int> customer_idcustomer { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_cake> order_cake { get; set; }
    }
}
