//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_cake
    {
        public int id { get; set; }
        public Nullable<int> order_idorder { get; set; }
        public string cake_idCake { get; set; }
        public Nullable<int> cake_quantity { get; set; }
    
        public virtual cake cake { get; set; }
        public virtual customer_order customer_order { get; set; }
    }
}
